import { Code } from "@/app/components/Code";
import styles from "./page.module.scss";
import { CURL_EXAMPLE_1, JSON_1, JSON_2, JSON_3, JSON_4, JSON_5 } from "./data";
import Link from "next/link";
import Toggle from "@/app/components/Toggle";
import { Steps } from "@/app/components/Steps";
// import curlExample from "./curl-1.txt";

export default function FundTransfer() {
  return (
    <div className={styles.container}>
      <aside className={styles.aside}>
        <ol>
          <li>
            <Link href="#initiate">Initiate</Link>
          </li>
          <li>
            <Link href="#track">Track</Link>
          </li>
          <li>
            <Link href="#reconcile">Reconcile</Link>
          </li>
        </ol>
      </aside>

      <article className={styles.article}>
        <header className={styles.header}>
          <h1 className={styles.h1}>Transfer Funds</h1>
          <div className="toggle">
            <Toggle defaultValue="swift" />
          </div>
        </header>

        {/* <h1 className={styles.h1}>Initiate A Funds Transfer With Pacs.008</h1> */}
        <section className={styles.section}>
          <h2>Initiate a payment</h2>
          <p>
            With the Funds Transfer API, you gain access to a secure and
            reliable solution that combines flexibility and global connectivity
            for all of your Funds Transfer needs. The Treasury Services Funds
            Transfer API solution enables you to send payments via high-value
            payment networks, either on your behalf or for your clients, in USD
            and more than 30 other currencies, using various MT and ISO 20022
            (MX) CBPR+ formats.
          </p>
          {/* <p>
            We developed our pacs.008 message schema based on Swift , a
            telecommunications company that specializes in connecting banks. The
            Swift messages are very flexible and built to accommodate many
            applications. To support this, in the pacs.008 message itself, there
            is an “envelope” – used just like the post office uses an actual
            envelope – it tells the delivery agent where to send the message.
          </p>
          <p>
            This use case takes you through the steps of executing a wire
            transfer using the BNY Funds Transfer API and the pacs.008 message
            format.
          </p> */}
        </section>
        <section className={styles.section}>
          <h2 className={styles.h2}>How It Works</h2>
          <Steps />
        </section>
        <section className={styles.section}>
          <h2>Payment Flow</h2>
          <p className={styles.lead}>
            pacs.008.001.0X (pacs.008) message - the ISO 20022 equivalent of
            existing MT 103, MT 103+, MT 103 Remit, MT 102 and MT 102+ messages
            – is part of the CBPR+ portfolio and is exchanged in the interbank
            cross-border leg of payments. It is sent by the debtor agent to the
            creditor agent – directly or through other agents and/or a payment
            clearing and settlement system – and is used to move funds from a
            debtor account to a creditor. It provides a structured way to
            communicate detailed payment instructions between financial
            institutions, ensuring accuracy and consistency in cross-border and
            domestic transactions. To use a pacs.008 message either the debtor,
            the creditor or both must be a non-financial institution.
          </p>
          <p>
            The message travels through the payment chain, ensuring that all
            intermediary banks and the final receiving bank have the necessary
            information to process the payment accurately. The structured format
            reduces the risk of errors and ensures compliance with various
            regulatory requirements.
          </p>
          <h3>Initiation</h3>
          <p>
            The ordering customer or institution initiates the wire transfer
            request through their financial institution, providing all necessary
            payment details, such as the amount, currency, and beneficiary
            information.
          </p>
          <h3>Message Creation</h3>
          <p>
            The pacs.008 message is generated by the initiating bank. This
            message is structured according to the ISO 20022 standard, including
            all relevant details such as debtor and creditor information,
            transaction amount, and any remittance information.
          </p>
          <h3>Transmission</h3>
          <p>
            The message is securely transmitted to the beneficiary’s bank
            through the Swift network or another secure financial messaging
            system. During this step, any intermediary banks involved in the
            payment chain also receive the message.
          </p>
          <h3>Settlement</h3>
          <p>
            Upon receiving the pacs.008 message, the beneficiary’s bank
            processes the payment according to the instructions provided. This
            includes verifying the details, ensuring compliance with local and
            international regulations, and applying the funds to the
            beneficiary’s account.
          </p>
          <h3>Confirmation</h3>
          <p>
            After processing, a confirmation message is sent back to the
            initiating bank, confirming that the payment has been successfully
            completed. The confirmation may include details of the payment
            status, any deductions (such as fees), and the final credited
            amount.
          </p>
          <p>
            This step-by-step process ensures that wire payments made using
            pacs.008 messages are accurate, secure, and compliant with
            international standards.
          </p>
        </section>
        <section className={styles.section}>
          <h2>Steps to Initiate a Wire Payment with Pacs.008</h2>
          <p>
            Before you begin, review the Prerequisites found on the top of this
            page.
          </p>
          <p>
            For full specifications for this API request, please visit the Funds
            Transfer Initiate Credit Transfer page. For full specifications on
            formatting the pacs.008 message, please visit the Swift BNY
            Standards page. Please note you must have credentials for the Swift
            website to view these. You can obtain Swift credentials by following
            the steps outlined here.
          </p>
          <p>
            The following depicts a high-level overview on how to structure a
            pacs.008 message.
          </p>

          <ol>
            <li>
              <h4>Endpoint</h4>
              <p>
                First, use this endpoint and set your headers to submit a Funds
                Transfer in the pacs.008 format.
              </p>
              <Code code={CURL_EXAMPLE_1} language="bash" />
            </li>
            <li>
              <h4>Format The Request Body</h4>
              <p>
                This API request body contains two required elements: metadata
                and request.
              </p>
              <p>
                The metadata represents the identifier and security controls for
                the request. Fields marked with an asterisk (*) are mandatory.
              </p>
              <table>
                <tbody>
                  <tr>
                    <td>requestId</td>
                    <td>Unique identifer for the request</td>
                  </tr>
                  <tr>
                    <td>idempotencyKey</td>
                    <td>For avoidance of duplicate payment submittal</td>
                  </tr>
                  <tr>
                    <td>signatureAlgorithm*</td>
                    <td>Digital signature algorithm</td>
                  </tr>
                  <tr>
                    <td>signature*</td>
                    <td>Digital signature to sign the payload</td>
                  </tr>
                </tbody>
              </table>
              <h5>Example</h5>
              <Code code={JSON_1.toString()} language="json" />
              <p>
                The request body represents the payment details. Fields marked
                with an asterisk (*) are mandatory.
              </p>
              <table>
                <tbody>
                  <tr>
                    <td>paymentProduct*</td>
                    <td>Payment product used to initiate the payment.</td>
                  </tr>
                  <tr>
                    <td>paymentMessage*</td>
                    <td>Type of payment being initiated.</td>
                  </tr>
                  <tr>
                    <td>messageFormat*</td>
                    <td>Format of the message being sent.</td>
                  </tr>
                  <tr>
                    <td>clientReferenceID</td>
                    <td>
                      Client-assigned reference ID to links payment to your
                      system.
                    </td>
                  </tr>
                  <tr>
                    <td>clientDescription</td>
                    <td>Memo field for your reference.</td>
                  </tr>
                  <tr>
                    <td>message*</td>
                    <td>
                      The pacs.008 formatted payment instruction, converted into
                      a JSON string.
                    </td>
                  </tr>
                </tbody>
              </table>
              <h5>Example</h5>
              <Code code={JSON_2.toString()} language="json" />
            </li>
            <li>
              <h4>Format The Message Field</h4>
              <ol>
                <li>
                  <h5>Overview</h5>
                  <p>
                    The pacs.008 message is a highly structured XML file that
                    includes detailed information about the payment, including
                    at a high level the following:
                  </p>
                  <ul>
                    <li>
                      Debtor Information: Details about the entity initiating
                      the payment.
                    </li>
                    <li>
                      Creditor Information: Details about the entity receiving
                      the payment.
                    </li>
                    <li>Transaction Amount: The amount being transferred.</li>
                    <li>
                      Currency: The currency in which the payment is made.
                    </li>
                    <li>
                      Payment Identification: Unique identifiers for the payment
                      to ensure traceability.
                    </li>
                    <li>
                      Remittance Information: Additional details that help the
                      recipient understand the purpose of the payment.
                    </li>
                  </ul>
                  <h5>Message Breakdown</h5>
                  <p>
                    The pacs.008 message is composed of several main components
                    with various sub-elements within them:
                  </p>
                  <ol>
                    <li>Application Header (AppHdr)</li>
                    <li>Group Header (GrpHdr)</li>
                    <li>
                      Credit Transfer Transaction Information (CdtTrfTxInf)
                    </li>
                  </ol>
                  <p>Pacs.008 Example:</p>
                  <Code code={JSON_3.toString()} language="json" />
                  <p>
                    The below is a breakdown of this sample pacs.008 message:
                  </p>
                  <ul>
                    <li>
                      Originator of the transaction: IRVTGB2XGTM (BNY GB
                      branch).
                    </li>
                    <li>
                      Sending To: IRVTUS3NAMS (Custody Branch 31, which is where
                      the debit account/settlement account sits).
                    </li>
                    <li>Debtor: Acme Inc. sending USD 300,000.</li>
                    <li>
                      To Creditor: Delta Lloyd with a Settlement Date of
                      2020-01-11
                    </li>
                    <li>
                      Debtor’s bank (agent): BIC is CHASGB2LXXX (Chase Bank)
                    </li>
                    <li>
                      Creditor’s bank (agent): BIC is ABNANL2AXXX (ABN Amro NL)
                    </li>
                    <li>
                      Intermediary bank (Agent): BIC is FTSBUS33XXX (ABN Amro
                      US) (Note: this is where Chase Bank is instructing us to
                      send the wire)
                    </li>
                  </ul>
                </li>
                <li>
                  <h5>Application Header</h5>
                  <p>
                    The Application Header is important for routing and
                    identifying the message within the Swift or other financial
                    messaging systems. In ISO20022, the Application Header is
                    used by the receiving organization to figure out where to
                    route the message in the same way. In the case of our API,
                    the “network” to which you drop your message is BNY’s own,
                    so you are essentially telling us to accept this message
                    from ourselves to deliver to ourselves.
                  </p>
                  <p>This header typically contains the following fields:</p>
                  <table>
                    <tbody>
                      <tr>
                        <th>
                          <strong>General Name</strong>
                        </th>
                        <th>
                          <strong>Pacs.008 Tag Name</strong>
                        </th>
                        <th>
                          <strong>Examples</strong>
                        </th>
                        <th>
                          <strong>More Information</strong>
                        </th>
                      </tr>
                      <tr>
                        <td>
                          <p>From</p>
                        </td>
                        <td>
                          <p>Fr.FinInstnId.BICFI</p>
                        </td>
                        <td>
                          <p>Example Value:</p>
                          <p>IRVTUS3NXXX</p>
                          <p>
                            <br />
                          </p>
                          <p>Example Full:</p>
                          <p>
                            &lt;Fr&gt;&lt;FIId&gt;&lt;FinInstnId&gt;&lt;BICFI&gt;
                            IRVTUS3NXXX
                            &lt;/BICFI&gt;&lt;/FinInstnId&gt;&lt;/FIId&gt;&lt;/Fr&gt;
                          </p>
                        </td>
                        <td>
                          <p>
                            The Business Identifier Code (BIC)* of the sending
                            financial institution (where the instructions are
                            coming from). The BICFI is an 8 or 11-character code
                            that uniquely identifies financial institutions
                            globally. This field identifies the sending
                            institution in the transaction and is critical for
                            routing and identifying the origin of the message
                            within the Swift network.
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>
                            If you do not have a BIC, IRVTUS3NXXX (or another
                            BNY BIC) can be used in both the From and To fields
                            of this message.
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>
                            *Code allocated to a financial institution by the
                            ISO 9362 Registration Authority as described in ISO
                            9362 "Banking - Banking telecommunication messages -
                            Business identifier code (BIC)".
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>To</p>
                        </td>
                        <td>
                          <p>To.FinInstnId.BICFI</p>
                        </td>
                        <td>
                          <p>Example Value:</p>
                          <p>IRVTUS3NAMS</p>
                          <p>
                            <br />
                          </p>
                          <p>Example Full:</p>
                          <p>
                            &lt;To&gt;&lt;FIId&gt;&lt;FinInstnId&gt;&lt;BICFI&gt;
                            IRVTUS3NAMS
                            &lt;/BICFI&gt;&lt;/FinInstnId&gt;&lt;/FIId&gt;&lt;/To&gt;
                          </p>
                        </td>
                        <td>
                          <p>
                            The BIC of the receiving financial institution.
                            Ensures the message reaches the correct recipient
                            institution.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Business Message Identifier</p>
                        </td>
                        <td>
                          <p>BizMsgIdr</p>
                        </td>
                        <td>
                          <p>MSG123456789</p>
                        </td>
                        <td>
                          <p>
                            A unique identifier for the message, typically a
                            combination of letters and numbers. Unambiguously
                            identifies the Business Message to the
                            MessagingEndpoint that has created the Business
                            Message.
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>Min/Max Value/Length: 1 - 35 characters</p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Message Definition Identifier</p>
                        </td>
                        <td>
                          <p>MsgDefIdr</p>
                        </td>
                        <td>
                          <p>pacs.008.001.08</p>
                        </td>
                        <td>
                          <p>
                            Contains the MessageIdentifier that defines the
                            BusinessMessage. It must contain a MessageIdentifier
                            published on the ISO 20022 website.
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>
                            For pacs.008, this will be "pacs.008.001.08" or a
                            similar identifier depending on the message version.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Business Service</p>
                        </td>
                        <td>
                          <p>BizSvc</p>
                        </td>
                        <td>
                          <p>swift.cbprplus.02</p>
                        </td>
                        <td>
                          <p>
                            Specifies the business service agreed between the
                            two MessagingEndpoints under which rules this
                            Business Message is exchanged. To be used when there
                            is a choice of processing services or processing
                            service levels.
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>
                            For pacs.008, this would typically be something like
                            "swiftpayment" or similar.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Creation Date</p>
                        </td>
                        <td>
                          <p>CreDt</p>
                        </td>
                        <td>
                          <p>2020-01-11T12:43:41.960+00:00</p>
                        </td>
                        <td>
                          <p>
                            Date when this Business Message (header) was
                            created. Note Times must be normalized, using the
                            "Z" annotation using the ISO 8601 UTC annotation.
                          </p>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </li>
                <li>
                  <h5>Group Header</h5>
                  <p>
                    This section contains general information about the message.
                    It typically contains the following fields:
                  </p>
                  <table>
                    <tbody>
                      <tr>
                        <th>
                          <strong>General Description</strong>
                        </th>
                        <th>
                          <strong>Pacs.008 Tag Name</strong>
                        </th>
                        <th>
                          <strong>Example</strong>
                        </th>
                        <th>
                          <strong>More Information</strong>
                        </th>
                      </tr>
                      <tr>
                        <td>
                          <p>Message Identification</p>
                        </td>
                        <td>
                          <p>MsgId</p>
                        </td>
                        <td>
                          <p>SS04044000000008</p>
                        </td>
                        <td>
                          <p>
                            Point to point reference, as assigned by the
                            instructing party, and sent to the next party in the
                            chain to unambiguously identify the message.
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>Min/Max Value/Length: 1 - 35 characters.</p>
                          <p>
                            <br />
                          </p>
                          <p>
                            Usage: The instructing party has to make sure that
                            MessageIdentification is unique per instructed party
                            for a pre-agreed period.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Creation Date Time</p>
                        </td>
                        <td>
                          <p>CreDtTm</p>
                        </td>
                        <td>
                          <p>2020-01-11T12:43:41.960+00:00</p>
                        </td>
                        <td>
                          <p>
                            Date and time at which the message was created. This
                            can be the same as the CreDt in the Application
                            Header.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Number Of Transactions</p>
                        </td>
                        <td>
                          <p>NbOfTxs</p>
                        </td>
                        <td>
                          <p>1</p>
                        </td>
                        <td>
                          <p>
                            Number of individual transactions contained in the
                            message. This remains consistent as long as you only
                            submit one transfer per message.
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>Max Value/Length: 15 characters</p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Settlement Method</p>
                        </td>
                        <td>
                          <p>SttlmInf.SttlmMtd</p>
                        </td>
                        <td>
                          <p>INDA</p>
                        </td>
                        <td>
                          <p>
                            Method used to settle the (batch of) payment
                            instructions.
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>Possible Enumeration: CLRG, INDA, INGA, COVE</p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>SettlementAccount</p>
                        </td>
                        <td>
                          <p>SttlmInf.SttlmAcct.Id.Othr.Id</p>
                        </td>
                        <td>
                          <p>9794728400</p>
                        </td>
                        <td>
                          <p>
                            A specific purpose account used to post debit and
                            credit entries as a result of the transaction. This
                            is the actual account to be debited.
                          </p>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </li>
                <li>
                  <h5>Credit Transfer Transaction Information</h5>
                  <p>
                    This section contains details about the actual credit
                    transfer instructions. It typically contains the following
                    fields:
                  </p>
                  <table>
                    <tbody>
                      <tr>
                        <th>
                          <strong>General Description</strong>
                        </th>
                        <th>
                          <strong>Pacs.008 Tag Name</strong>
                        </th>
                        <th>
                          <strong>Example Value</strong>
                        </th>
                        <th>
                          <strong>More Information</strong>
                        </th>
                      </tr>
                      <tr>
                        <td>
                          <p>Instruction Identification</p>
                        </td>
                        <td>
                          <p>PmtId.InstrId</p>
                        </td>
                        <td>
                          <p>SS04044506272708</p>
                        </td>
                        <td>
                          <p>
                            Unique identification, as assigned by an instructing
                            party for an instructed party, to unambiguously
                            identify the instruction. This is an ID assigned by
                            the client and needs to be the same as the
                            EndToEndID (35 char).
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>
                            Usage: The instruction identification is a
                            point-to-point reference that can be used between
                            the instructing party and the instructed party to
                            refer to the individual instruction. It can be
                            included in several messages related to the
                            instruction.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>End To End Identification</p>
                        </td>
                        <td>
                          <p>PmtId.EndToEndId</p>
                        </td>
                        <td>
                          <p>KK04044506200000</p>
                        </td>
                        <td>
                          <p>
                            Unique identification, as assigned by the initiating
                            party, to unambiguously identify the transaction.
                            This identification is passed on, unchanged,
                            throughout the entire end-to-end chain. This is an
                            ID assigned by the client and needs to be the same
                            as the PmtId (35 char).
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>
                            Usage: Usage: In case there are technical
                            limitations to pass on multiple references, the
                            end-to-end identification must be passed on
                            throughout the entire end-to-end chain.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>UETR</p>
                        </td>
                        <td>
                          <p>PmtId.UETR</p>
                        </td>
                        <td>
                          <p>12345678-0000-4000-B000-123456781234</p>
                        </td>
                        <td>
                          <p>
                            Universally unique identifier to provide an
                            end-to-end reference of a payment transaction. (UUID
                            v4 format).
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Interbank Settlement Amount</p>
                        </td>
                        <td>
                          <p>IntrBkSttlmAmt</p>
                        </td>
                        <td>
                          <p>300000</p>
                        </td>
                        <td>
                          <p>
                            The amount of money to be settled between the
                            financial institutions involved in the transaction.
                            Should be populated with the same amount in
                            InstdAmt.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Interbank Settlement Date</p>
                        </td>
                        <td>
                          <p>IntrBkSttlmDt</p>
                        </td>
                        <td>
                          <p>1/11/2020</p>
                        </td>
                        <td>
                          <p>
                            The date on which the settlement amount is to be
                            settled between the financial institutions involved.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Instructed Amount</p>
                        </td>
                        <td>
                          <p>InstdAmt</p>
                        </td>
                        <td>
                          <p>300000</p>
                        </td>
                        <td>
                          <p>
                            Amount of money to be moved between the debtor and
                            creditor, before deduction of charges, expressed in
                            the currency as ordered by the initiating party.
                            Usage: This amount has to be transported unchanged
                            through the transaction chain.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>ChargeBearer</p>
                        </td>
                        <td>
                          <p>ChrgBr</p>
                        </td>
                        <td>
                          <p>DEBT</p>
                        </td>
                        <td>
                          <p>
                            Specifies which party/parties will bear the charges
                            associated with the processing of the payment
                            transaction.
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>Enumeration: DEBT, SHAR, or CRED.</p>
                          <p>
                            <br />
                          </p>
                          <ul>
                            <li>DEBT : charges borne be debtor.</li>
                            <li>
                              SHAR : charges are shared between the debtor and
                              creditor.
                            </li>
                            <li>CRED : all charges borne by the creditor.</li>
                          </ul>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Instructed Agent</p>
                        </td>
                        <td>
                          <p>InstdAgt.FinInstnId.BICFI</p>
                        </td>
                        <td>
                          <p>IRVTGB2XGTM</p>
                        </td>
                        <td>
                          <p>
                            Agent that is instructed by the previous party in
                            the chain to carry out the (set of) instruction(s).
                            Clients BIC, BIC must match the BIC in the header.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Instructing Agent</p>
                        </td>
                        <td>
                          <p>InstgAgt.FinInstnId.BICFI</p>
                        </td>
                        <td>
                          <p>IRVTUS3NAMS</p>
                        </td>
                        <td>
                          <p>
                            Agent that instructs the next party in the chain to
                            carry out the (set of) instruction(s).
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>
                            IRVTUS3NAMS or IRVTUS3NXXX, BIC must match the BIC
                            in the header.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Intermediary Agent 1</p>
                        </td>
                        <td>
                          <p>IntrmyAgt1.FinInstnId.BICFI</p>
                        </td>
                        <td>
                          <p>FTSBUS33XXX</p>
                        </td>
                        <td>
                          <p>
                            Agent between the debtor's agent and the creditor's
                            agent.
                          </p>
                          <p>
                            <br />
                          </p>
                          <p>
                            Usage: If more than one intermediary agent is
                            present, then IntermediaryAgent1 identifies the
                            agent between the DebtorAgent and the
                            IntermediaryAgent2.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Debtor Name</p>
                        </td>
                        <td>
                          <p>Dbtr.Nm</p>
                        </td>
                        <td>
                          <p>ACME INC.</p>
                        </td>
                        <td>
                          <p>This is the original requestor of the funds.</p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Debtor Agent</p>
                        </td>
                        <td>
                          <p>DbtrAgt.FinInstnId.BICFI</p>
                        </td>
                        <td>
                          <p>CHASGB2LXXX</p>
                        </td>
                        <td>
                          <p>
                            Financial institution servicing an account for the
                            debtor.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Creditor Name</p>
                        </td>
                        <td>
                          <p>Cdtr.Nm</p>
                        </td>
                        <td>
                          <p>DELTA LLOYD</p>
                        </td>
                        <td>
                          <p>
                            This is the final Beneficiary of the fund's name
                            &amp; addressCdtr.PstlAdr.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Creditor Address</p>
                        </td>
                        <td>
                          <p>PstlAdr.StrtNm.PstCd.TwnNm.Ctry</p>
                        </td>
                        <td>
                          <p>OMVAL 30000000 TOWN2 NL</p>
                        </td>
                        <td>
                          <p>Postal address of the creditor.</p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Creditor Agent</p>
                        </td>
                        <td>
                          <p>CdtrAgt.FinInstnId.BICFI</p>
                        </td>
                        <td>
                          <p>ABNANL2AXXX</p>
                        </td>
                        <td>
                          <p>
                            Financial institution servicing an account for the
                            creditor.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Creditor Account</p>
                        </td>
                        <td>
                          <p>CdtrAcct.Id.Othr.Id</p>
                        </td>
                        <td>
                          <p>NL00ABNA0123456789</p>
                        </td>
                        <td>
                          <p>
                            Unambiguous identification of the account of the
                            creditor to which a credit entry will be posted as a
                            result of the payment transaction. This is the final
                            Beneficiary's Account.
                          </p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <p>Remittance Information</p>
                        </td>
                        <td>
                          <p>RmtInf.Ustrd</p>
                        </td>
                        <td>
                          <p>INVOICE A000,0000/04,991/05</p>
                        </td>
                        <td>
                          <p>
                            Information supplied to enable the matching of an
                            entry with the items that the transfer is intended
                            to settle, such as commercial invoices in an
                            account's receivable system.
                          </p>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </li>
              </ol>
            </li>
            <li>
              <h4>Receive An API Response</h4>
              <p>
                The Response Body contains two elements: metadata and result.
              </p>
              <table>
                <tbody>
                  <tr>
                    <th>success</th>
                    <td>Indicates whether the API call was successful</td>
                  </tr>
                  <tr>
                    <th>requestId</th>
                    <td>Request identifier that was sent in the API request</td>
                  </tr>
                  <tr>
                    <th>count</th>
                    <td>Number of records returned in the response</td>
                  </tr>
                  <tr>
                    <th>xrefID</th>
                    <td>
                      Unique system-generated reference ID for the payment
                      initiation request
                    </td>
                  </tr>
                  <tr>
                    <th>clientReferenceId</th>
                    <td>
                      Internal reference ID of the client that links the payment
                      to their system
                    </td>
                  </tr>
                  <tr>
                    <th>timeReceived</th>
                    <td>
                      Date and time the payment request was received by the
                      system
                    </td>
                  </tr>
                  <tr>
                    <th>clientDescription</th>
                    <td>Memo field for client reference</td>
                  </tr>
                  <tr>
                    <th>status</th>
                    <td>
                      Payment status; "Received" is the only valid response for
                      a successful request. Otherwise, an error will be
                      returned.
                    </td>
                  </tr>
                </tbody>
              </table>
              <Code code={JSON_4.toString()} language="json" />
              <p>
                If you receive an error, the 'success' field in the response
                will be returned as false. An example of a
                <Link href="https://marketplace.bnymellon.com/treasury/api-library/general-errors">
                  General API Error
                </Link>
                is found below.
              </p>
              <Code code={JSON_5.toString()} language="json" />
              <p>
                You may also receive an
                <Link href="https://marketplace.bnymellon.com/treasury/api-central/#/pacs008:~:text=You%20may%20also%20receive%20an%20API%20Gateway%20error%20which%20are%20caused%20by%20authorization%20problems%20with%20the%20request%20at%20the%20BNY%20API%20Gateway.">
                  API Gateway error
                </Link>
                which are caused by authorization problems with the request at
                the BNY API Gateway.
              </p>
            </li>
            <li>
              <h4>Track Your Payment</h4>
              <p>
                Next up,{" "}
                <Link href="https://marketplace.bnymellon.com/treasury/api-central/#/tracking">
                  track your payment
                </Link>{" "}
                and{" "}
                <Link href="https://marketplace.bnymellon.com/treasury/api-central/#/pacs008:~:text=Next%20up%2C%20track%20your%20payment%20and%20set%20up%20your%20funds%20transfer%20notifications.">
                  set up your funds transfer notifications
                </Link>
                .
              </p>
            </li>
          </ol>
        </section>
      </article>
    </div>
  );
}
