import { FinancialMessagingStandard } from "@/app/features/types";
import { useContext } from "react";
import { InViewItem } from "../../context/in-view";
import { UserConfigContext } from "../../context/user-config";
import { Beneficiary } from "../../icons/Beneficiary";
import { BeneficiaryBank } from "../../icons/BeneficiaryBank";
import { Currencies } from "../../icons/Currencies";
import { Customer } from "../../icons/Customer";
import { IntermediaryBank } from "../../icons/IntermediaryBank";
import { MoneyTransaction } from "../../icons/MoneyTransaction";
import { WebsiteEndpoint } from "../../icons/WebsiteEndpoint";
import { Step } from "../Step";
import styles from "./index.module.scss";

export function TimelineCards() {
  const { config } = useContext(UserConfigContext);
  const { messagingStandard } = config;

  switch (messagingStandard) {
    case FinancialMessagingStandard.SWIFT:
      return (
        <ol className={styles.steps}>
          <li>
            <Step
              itemId={InViewItem.Customer}
              icon={<Customer />}
              tag="Initiation"
              title="Ordering Customer"
              description="A customer initiates a wire transfer."
            />
          </li>

          <li>
            <Step
              itemId={InViewItem.ClientHostApplication}
              icon={<WebsiteEndpoint />}
              tag="Initiation"
              title="Client Host Application"
              path="/payments"
              description="Our /payments API endpoint, receives details such as the sender's and recipient's bank information, amount, and currency."
            />
          </li>

          <li>
            <Step
              itemId={InViewItem.OrderingInstitution}
              icon={<MoneyTransaction />}
              tag="Message Creation"
              title="Ordering Institution"
              description="The MT 103 message is created, containing all necessary details for the transfer."
            />
          </li>

          <li>
            <Step
              itemId={InViewItem.IntermediaryBankA}
              icon={<IntermediaryBank />}
              tag="Transmission"
              title="Intermediary Bank A"
              description="The message is transmitted through the Swift network to the recipient's bank."
            />
          </li>

          <li>
            <Step
              itemId={InViewItem.IntermediaryBankB}
              icon={<Currencies />}
              tag="Transmission"
              title="Intermediary Bank B"
              description="Multiple intermediary banks can be involved in case of currency exchange."
            />
          </li>

          <li>
            <Step
              itemId={InViewItem.BeneficiaryBank}
              icon={<BeneficiaryBank />}
              tag="Processing"
              title="Beneficiary Bank"
              description="The recipient's bank processes the message and credits the recipient's account."
            />
          </li>

          <li>
            <Step
              itemId={InViewItem.Beneficiary}
              icon={<Beneficiary />}
              tag="Confirmation"
              title="Beneficiary"
              description="Confirmation of the transfer is sent back to the sender, completing the transaction."
            />
          </li>
        </ol>
      );

    case FinancialMessagingStandard.PACS:
      return (
        <ol className={styles.steps}>
          <li>
            <Step
              itemId={InViewItem.Customer}
              icon={<Customer />}
              tag="Initiation"
              title="Debtor"
              description="The ordering customer or institution initiates the wire transfer request through their financial institution, providing all necessary payment details, such as the amount, currency, and beneficiary information."
            />
          </li>

          <li>
            <Step
              itemId={InViewItem.ClientHostApplication}
              icon={<WebsiteEndpoint />}
              tag="Message Creation"
              title="Client Host Application"
              path="/payments"
              description="The pacs.008 message is generated by the initiating bank. This
          message is structured according to the ISO 20022 standard,
          including all relevant details such as debtor and creditor
          information, transaction amount, and any remittance information."
            />
          </li>

          <li>
            <Step
              itemId={InViewItem.DebtorAgent}
              icon={<Currencies />}
              tag="Transmission"
              title="Debtor Agent"
              description="The message is securely transmitted to the beneficiary's
          bank through the Swift network or another secure financial
          messaging system."
            />
          </li>

          <li>
            <Step
              itemId={InViewItem.IntermediaryAgent}
              icon={<IntermediaryBank />}
              tag="Transmission"
              title="Intermediary Agent 1"
              description="Any intermediary banks
          involved in the payment chain also receive the message."
            />
          </li>

          <li>
            <Step
              itemId={InViewItem.CreditorAgent}
              icon={<BeneficiaryBank />}
              tag="Processing"
              title="Creditor Agent"
              description="Upon receiving the pacs.008 message, the beneficiary's bank
          processes the payment according to the instructions provided.
          This includes verifying the details, ensuring compliance with
          local and international regulations, and applying the funds to
          the beneficiary's account."
            />
          </li>

          <li>
            <Step
              itemId={InViewItem.Creditor}
              icon={<Beneficiary />}
              tag="Confirmation"
              title="Creditor"
              description="After processing, a confirmation message is sent back to the
          initiating bank, confirming that the payment has been
          successfully completed. The confirmation may include details of
          the payment status, any deductions (such as fees), and the final
          credited amount."
            />
          </li>
        </ol>
      );
  }
}
